#!/usr/bin/env python3
"""
Bootstrap a VEHU-style container (e.g. vehu10): copy routine-sync scripts, clone FHIR repos
inside the container, sync src/*.m to the M routine directory, optionally ZL + D EN^SYNWEBRG.

Typical vehu10 HTTP base: http://127.0.0.1:9085/

For a quick **Server-Codex-only** sync (no git clone inside the container), use
**scripts/vehu10-fhir-sync.sh** — same host/port/user/routine dir as this bootstrap.

Requires: docker CLI, container user with git and bash (git often present on vehu images).

Example:
  ./scripts/vehu10_bootstrap.py --container vehu10 --register-routes --restart-webreq
  # Default: Data-Loader = glilly + vaready-wd-compat; Server-Codex = WorldVistA + master
  # Same branch on both repos (only if that branch exists in both):
  ./scripts/vehu10_bootstrap.py --container vehu10 --dev-branch topic/my-feature

Env:
  VEHU_BOOTSTRAP_LOADER_ORG   GitHub org for Data-Loader (default: glilly)
  VEHU_BOOTSTRAP_CODEX_ORG    GitHub org for Server-Codex (default: WorldVistA)
  VEHU_BOOTSTRAP_GH_ORG       If set, same org for BOTH repos (overrides loader/codex org args)
  VEHU_ROUTINE_DEV_BRANCH     Default branch for Data-Loader when --loader-branch omitted (default: vaready-wd-compat)
  VEHU_ROUTINE_LOADER_BRANCH  Overrides Data-Loader branch (wins over VEHU_ROUTINE_DEV_BRANCH)
  VEHU_ROUTINE_CODEX_BRANCH   Server-Codex branch (default: master if unset, unless --dev-branch sets both)
"""
from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def run(cmd: list[str], *, check: bool = True, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, text=True, **kwargs)


def docker_cp(src: Path, container: str, dest: str) -> None:
    run(["docker", "cp", str(src), f"{container}:{dest}"])


def write_repos_conf(
    path: Path,
    *,
    loader_org: str,
    codex_org: str,
    loader_branch: str,
    codex_branch: str,
    loader_repo: str,
    codex_repo: str,
) -> None:
    lines = [
        f"# Generated by vehu10_bootstrap.py — branches pinned here; routine-sync always checks out these refs.",
        f"data-loader|https://github.com/{loader_org}/{loader_repo}.git|{loader_branch}|src",
        f"server-codex|https://github.com/{codex_org}/{codex_repo}.git|{codex_branch}|src",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description="Bootstrap vehu10 (or similar) with FHIR M routines.")
    p.add_argument("--container", default="vehu10", help="Docker container name (default: vehu10)")
    p.add_argument(
        "--routine-dest",
        default="/home/vehu/p",
        help="Directory in container for .m sources (default: /home/vehu/p)",
    )
    p.add_argument(
        "--bootstrap-dir",
        default="/home/vehu/opt/fhir-bootstrap",
        help="Directory in container for sync scripts (created if missing)",
    )
    p.add_argument(
        "--vehu-user", default="vehu", help="User for docker exec -u (default: vehu)"
    )
    p.add_argument(
        "--vehu-env",
        default="/home/vehu/etc/env",
        help="Optional env file sourced before mumps (default: /home/vehu/etc/env)",
    )
    p.add_argument(
        "--dev-branch",
        default=None,
        metavar="BRANCH",
        help="Set this branch on BOTH repos (overrides per-repo defaults)",
    )
    p.add_argument(
        "--loader-branch",
        default=None,
        metavar="BRANCH",
        help="Data-Loader branch (default: VEHU_ROUTINE_LOADER_BRANCH or VEHU_ROUTINE_DEV_BRANCH or vaready-wd-compat)",
    )
    p.add_argument(
        "--codex-branch",
        default=None,
        metavar="BRANCH",
        help="Server-Codex branch (default: VEHU_ROUTINE_CODEX_BRANCH or master, or --dev-branch for both)",
    )
    p.add_argument(
        "--loader-org",
        default=os.environ.get("VEHU_BOOTSTRAP_LOADER_ORG", "glilly"),
        help="GitHub org for VistA-FHIR-Data-Loader",
    )
    p.add_argument(
        "--codex-org",
        default=os.environ.get("VEHU_BOOTSTRAP_CODEX_ORG", "WorldVistA"),
        help="GitHub org for VistA-FHIR-Server-Codex",
    )
    p.add_argument(
        "--gh-org",
        default=os.environ.get("VEHU_BOOTSTRAP_GH_ORG", None),
        metavar="ORG",
        help="If set, use this org for BOTH repos (overrides --loader-org and --codex-org)",
    )
    p.add_argument(
        "--loader-repo",
        default="VistA-FHIR-Data-Loader",
        help="Data loader repository name on GitHub",
    )
    p.add_argument(
        "--codex-repo",
        default="VistA-FHIR-Server-Codex",
        help="Server-Codex repository name on GitHub",
    )
    p.add_argument(
        "--skip-git",
        action="store_true",
        help="Do not run clone/pull/sync inside the container",
    )
    p.add_argument(
        "--register-routes",
        action="store_true",
        help="After sync, ZL SYNWEBRG and D EN^SYNWEBRG via mumps -dir",
    )
    p.add_argument(
        "--restart-webreq",
        action="store_true",
        help="After --register-routes, run D stop^%webreq D go^%webreq",
    )
    p.add_argument(
        "--http-smoke-url",
        default="http://127.0.0.1:9085/",
        help="Printed at end for manual curl check (default vehu10 portal)",
    )
    args = p.parse_args()

    default_loader = os.environ.get("VEHU_ROUTINE_DEV_BRANCH", "vaready-wd-compat")
    cli_dev = args.dev_branch
    if args.loader_branch is not None:
        loader_branch = args.loader_branch
    elif os.environ.get("VEHU_ROUTINE_LOADER_BRANCH"):
        loader_branch = os.environ["VEHU_ROUTINE_LOADER_BRANCH"]
    elif cli_dev is not None:
        loader_branch = cli_dev
    else:
        loader_branch = default_loader

    if args.codex_branch is not None:
        codex_branch = args.codex_branch
    elif os.environ.get("VEHU_ROUTINE_CODEX_BRANCH"):
        codex_branch = os.environ["VEHU_ROUTINE_CODEX_BRANCH"]
    elif cli_dev is not None:
        codex_branch = cli_dev
    else:
        codex_branch = "master"

    if args.gh_org:
        loader_org = codex_org = args.gh_org
    else:
        loader_org = args.loader_org
        codex_org = args.codex_org

    print(
        f"Repos: Data-Loader github.com/{loader_org}/{args.loader_repo}@{loader_branch!r} "
        f"Server-Codex github.com/{codex_org}/{args.codex_repo}@{codex_branch!r}",
        file=sys.stderr,
    )

    root = repo_root()
    sync_script = root / "scripts" / "routine-sync.sh"
    if not sync_script.is_file():
        print(f"error: missing {sync_script}", file=sys.stderr)
        return 1

    synwebrg = root / "src" / "SYNWEBRG.m"
    if not synwebrg.is_file():
        print(f"error: missing {synwebrg}", file=sys.stderr)
        return 1

    c = args.container
    bdir = args.bootstrap_dir.rstrip("/")
    routine_dest = args.routine_dest.rstrip("/")
    u = args.vehu_user

    run(
        [
            "docker",
            "exec",
            c,
            "bash",
            "-lc",
            "mkdir -p "
            + shlex.quote(bdir)
            + " /home/vehu/vista-routine-src && chown -R "
            + shlex.quote(u)
            + ":"
            + shlex.quote(u)
            + " "
            + shlex.quote(bdir)
            + " /home/vehu/vista-routine-src",
        ],
        check=True,
    )

    docker_cp(sync_script, c, f"{bdir}/routine-sync.sh")

    with tempfile.NamedTemporaryFile(
        mode="w", suffix="-routine-sync-repos.conf", delete=False, encoding="utf-8"
    ) as tf:
        tpath = Path(tf.name)
    try:
        write_repos_conf(
            tpath,
            loader_org=loader_org,
            codex_org=codex_org,
            loader_branch=loader_branch,
            codex_branch=codex_branch,
            loader_repo=args.loader_repo,
            codex_repo=args.codex_repo,
        )
        docker_cp(tpath, c, f"{bdir}/routine-sync-repos.conf")
    finally:
        tpath.unlink(missing_ok=True)

    run(
        [
            "docker",
            "exec",
            c,
            "bash",
            "-lc",
            "chown "
            + shlex.quote(u)
            + ":"
            + shlex.quote(u)
            + " "
            + shlex.quote(f"{bdir}/routine-sync.sh")
            + " "
            + shlex.quote(f"{bdir}/routine-sync-repos.conf")
            + " && chmod a+x "
            + shlex.quote(f"{bdir}/routine-sync.sh"),
        ],
        check=True,
    )

    if not args.skip_git:
        env_export = (
            f"export ROUTINE_SYNC_CONFIG={bdir}/routine-sync-repos.conf "
            f"ROUTINE_SYNC_ROOT=/home/vehu/vista-routine-src "
            f"ROUTINE_SYNC_DEST={routine_dest}"
        )
        inner = (
            f"set -euo pipefail; "
            f"command -v git >/dev/null || {{ echo 'error: git not installed in container' >&2; exit 1; }}; "
            f"{env_export}; "
            f"'{bdir}/routine-sync.sh' clone && "
            f"'{bdir}/routine-sync.sh' sync"
        )
        r = run(
            [
                "docker",
                "exec",
                "-u",
                args.vehu_user,
                c,
                "bash",
                "-lc",
                inner,
            ],
            check=False,
        )
        if r.returncode != 0:
            print("error: clone/sync failed inside container", file=sys.stderr)
            return r.returncode or 1

    # After sync so this copy wins over the repo until SYNWEBRG.m is pushed
    docker_cp(synwebrg, c, f"{routine_dest}/SYNWEBRG.m")
    run(
        [
            "docker",
            "exec",
            c,
            "bash",
            "-lc",
            "chown "
            + shlex.quote(u)
            + ":"
            + shlex.quote(u)
            + " "
            + shlex.quote(f"{routine_dest}/SYNWEBRG.m"),
        ],
        check=True,
    )

    if args.register_routes:
        env_src = f"source {args.vehu_env} >/dev/null 2>&1; "
        mumps_in = (
            'ZL "SYNINIT"\n'
            'ZL "SYNWEBRG"\n'
            "D EN^SYNWEBRG\n"
            + (
                "D stop^%webreq D go^%webreq\n"
                if args.restart_webreq
                else ""
            )
            + "H\n"
        )
        r = run(
            [
                "docker",
                "exec",
                "-i",
                "-u",
                args.vehu_user,
                c,
                "bash",
                "-lc",
                env_src + "mumps -dir",
            ],
            input=mumps_in,
            check=False,
        )
        if r.returncode != 0:
            print("error: mumps registration failed", file=sys.stderr)
            return r.returncode or 1

    print("Bootstrap steps finished.")
    print(f"  Container: {c}  routines: {routine_dest}")
    print(f"  Portal smoke URL (host): {args.http_smoke_url}")
    print("  If routes were not registered: ZL \"SYNINIT\" ZL \"SYNWEBRG\" then D EN^SYNWEBRG")
    print("  Reload other changed routines with ZL as needed, then XINDEX per site policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
