C0FR69X ; VEHU/Codex - residual R69 POV narrative → better ICD ;Sep 24, 2026
 ;;0.1;C0FHIR PROJECT;;Sep 24, 2026
 ;
 ; P3 hygiene: remap common Synthea R69 encounter diagnoses by narrative to
 ; a more specific ICD-10 when Lexicon previously caught-all'd. Does not
 ; invent measure membership for CQL — just cleaner Condition coding.
 ;
 Q
 ;
GO ; Scan all V POV; fix R69 rows with known narratives
 N ICD,NARR,POV,R69,X0,MAP,N,U
 S U="^"
 S R69=+$$ICDDX^ICDEX("R69.",30) I R69<1 W "no R69",! Q
 S POV=0,N=0
 F  S POV=$O(^AUPNVPOV(POV)) Q:'POV  D
 . S X0=$G(^AUPNVPOV(POV,0))
 . Q:+$P(X0,U)'=R69
 . S NARR=$$UP^XLFSTR($P($G(^AUTNPOV(+$P(X0,U,4),0)),U))
 . S MAP=$$MAP(NARR) Q:MAP=""
 . S ICD=+$$ICDDX^ICDEX(MAP,30) Q:ICD<1
 . S $P(^AUPNVPOV(POV,0),U)=ICD
 . S N=N+1
 . W "POV ",POV," R69→",MAP," ",$E(NARR,1,40),!
 W "fixed ",N,!
 Q
 ;
MAP(N) ; $$ - narrative → ICD-10-CM
 I N["GINGIVITIS"!(N["GINGIVAL") Q "K05.10"
 I N["STRESS (FINDING)"!(N["STRESS") Q "Z73.3"
 I N["SOCIAL ISOLATION" Q "Z60.4"
 I N["UNEMPLOY" Q "Z56.0"
 I N["SLEEP DISORDER"!(N["SLEEP APNEA") Q "G47.9"
 I N["CHRONIC PAIN" Q "G89.29"
 I N["ANEMIA" Q "D64.9"
 I N["VIRAL SINUSITIS"!(N["SINUSITIS") Q "J01.90"
 I N["OBESITY"!(N["BODY MASS INDEX 30") Q "E66.9"
 I N["OSTEOARTHRITIS OF KNEE" Q "M17.9"
 I N["OSTEOARTHRITIS OF HIP" Q "M16.9"
 I N["NORMAL PREGNANCY" Q "Z34.90"
 I N["COMPLETE MISCARRIAGE"!(N["MISCARRIAGE") Q "O03.9"
 I N["HYPERTRIGLYCERIDEMIA" Q "E78.1"
 I N["METABOLIC SYNDROME" Q "E88.81"
 I N["CHRONIC KIDNEY DISEASE STAGE 3" Q "N18.3"
 I N["CHRONIC KIDNEY DISEASE STAGE 2" Q "N18.2"
 I N["CHRONIC KIDNEY DISEASE STAGE 1" Q "N18.1"
 I N["ISCHEMIC HEART" Q "I25.9"
 I N["DIABETES MELLITUS TYPE 2"!(N["DIABETES MELLITUS TYPE II")!(N["TYPE 2 DIABETES") Q "E11.9"
 I N["ESSENTIAL HYPERTENSION"!(N["HYPERTENS") Q "I10"
 I N["OTITIS MEDIA" Q "H66.90"
 I N["APPENDICITIS" Q "K35.80"
 I N["ACUTE BRONCHITIS"!(N["BRONCHITIS") Q "J20.9"
 I N["ALLERGIC RHINITIS"!(N["PERENNIAL ALLERGIC") Q "J30.9"
 I N["ALLERGIC DISPOSITION" Q "Z91.09"
 I N["LACERATION" Q "T14.8"
 I N["SPRAIN OF WRIST"!(N["SPRAIN") Q "S63.90XA"
 I N["CYSTITIS" Q "N30.90"
 I N["MIGRAINE" Q "G43.909"
 I N["TRANSPORT PROBLEM" Q "Z59.8"
 I N["LOSS OF TEETH" Q "K08.109"
 I N["CORONARY ARTERY BYPASS"!(N["HISTORY OF CORONARY") Q "Z95.1"
 I N["LEAKING DENTAL"!(N["DENTAL FILLING") Q "K08.59"
 I N["BURN" Q "T30.0"
 I N["ANXIETY"!(N["PANIC") Q "F41.9"
 I N["LOW BACK PAIN"!(N["BACK PAIN") Q "M54.5"
 I N["FULL THICKNESS BURN" Q "T30.0"
 I N["MALIGNANT NEOPLASM OF BREAST"!(N["NEOPLASM OF BREAST") Q "C50.919"
 I N["CONCUSSION" Q "S06.0X0A"
 I N["FRACTURE OF BONE"!(N["FRACTURE") Q "T14.8"
 I N["INJURY OF NECK" Q "S19.9XXA"
 I N["FETUS WITH UNKNOWN"!(N["FETUS") Q "O36.80X0"
 I (N["PROTEINURIA")&(N["DIABET") Q "E11.21"
 I N["ACUTE RESPIRATORY DISTRESS" Q "J80"
 I N["ALVEOLITIS" Q "K10.3"
 Q ""
 ;
